import {
  BKMVDATASchema,
  Cell,
  DocumentPayment,
  DocumentRecord,
  HasBranches,
  PaymentMethod,
  Row,
  SoftwareAccountingType,
} from '../types'
import { C100Schema } from './C100Schema'
import { D110Schema } from './D110Schema'
import { D120Schema } from './D120Schema'
import { B100Schema } from './B100Schema'
import { B110Schema } from './B110Schema'
import { M100Schema } from './M100Schema'

const header: Row = {
  cells: [
    {
      fieldId: 1100,
      name: 'recordCode',
      description: 'קוד רשומה',
      type: 'string',
      length: 4,
      startAt: 1,
      endAt: 4,
      required: true,
      default: 'A100',
    },
    {
      fieldId: 1101,
      name: 'runningNumber',
      description: 'מס רשומה בקובץ',
      type: 'number',
      length: 9,
      startAt: 5,
      endAt: 13,
      required: true,
    },
    {
      fieldId: 1102,
      name: 'business.taxId',
      description: 'מספר עוסק מורשה',
      type: 'number',
      length: 9,
      startAt: 14,
      endAt: 22,
      required: true,
    },
    {
      fieldId: 1103,
      name: 'uuid',
      description: 'מזהה ראשי',
      type: 'number',
      length: 15,
      startAt: 23,
      endAt: 37,
      required: true,
    },
    {
      fieldId: 1104,
      name: 'systemConstant',
      description: 'קבוע מערכת',
      type: 'string',
      length: 8,
      startAt: 38,
      endAt: 45,
      required: true,
      default: '&OF1.31&',
    },
    {
      fieldId: 1105,
      name: 'forFutureData',
      description: 'שטח לנתונים עתידיים',
      type: 'string',
      length: 50,
      startAt: 46,
      endAt: 95,
      required: false,
    },
  ],
}
const footer: Row = {
  cells: [
    {
      fieldId: 1150,
      name: 'recordCode',
      description: 'קוד רשומה',
      type: 'string',
      length: 4,
      startAt: 1,
      endAt: 4,
      required: true,
      default: 'Z900',
    },
    {
      fieldId: 1151,
      name: 'runningNumber',
      description: 'מס רשומה בקובץ',
      type: 'number',
      length: 9,
      startAt: 5,
      endAt: 13,
      required: true,
    },
    {
      fieldId: 1152,
      name: 'business.taxId',
      description: 'מספר עוסק מורשה',
      type: 'number',
      length: 9,
      startAt: 14,
      endAt: 22,
      required: true,
    },
    {
      fieldId: 1153,
      name: 'uuid',
      description: 'מזהה ראשי',
      type: 'number',
      length: 15,
      startAt: 23,
      endAt: 37,
      required: true,
    },
    {
      fieldId: 1154,
      name: 'systemConstant',
      description: 'קבוע מערכת',
      type: 'string',
      length: 8,
      startAt: 38,
      endAt: 45,
      required: true,
      default: '&OF1.31&',
    },
    {
      fieldId: 1155,
      name: 'totalRecords',
      description: 'סך רשומות כולל בקובץ',
      type: 'number',
      length: 15,
      startAt: 46,
      endAt: 60,
      required: true,
    },
    {
      fieldId: 1155,
      name: 'forFutureData',
      description: 'שטח לנתונים עתידיים',
      type: 'string',
      length: 50,
      startAt: 61,
      endAt: 110,
      required: false,
    },
  ],
}

// Create an enum in english from the documentTypes array
export const bkmvdataSchema: BKMVDATASchema = {
  header,
  footer,
  C100: C100Schema,
  D110: D110Schema,
  D120: D120Schema,
  B100: B100Schema,
  B110: B110Schema,
  M100: M100Schema,
}
