import {BKMVDATAFormat} from "../types";

export const bkmvdataFormat: BKMVDATAFormat = {
    header: {
        cells: [
            {
                fieldId: 1100,
                description: 'קוד רשומה',
                type: 'string',
                length: 4,
                startAt: 1,
                endAt: 4,
                required: true,
                default: 'A100',
            },
            {
                fieldId: 1101,
                description: 'מס רשומה בקובץ',
                type: 'number',
                length: 9,
                startAt: 5,
                endAt: 13,
                required: true,
                default: 0,
            },
            {
                fieldId: 1102,
                description: 'מספר עוסק מורשה',
                type: 'number',
                length: 9,
                startAt: 14,
                endAt: 22,
                required: true,
                default: 0,
            },
            {
                fieldId: 1103,
                name: 'uuid',
                description: 'מזהה ראשי',
                type: 'number',
                length: 15,
                startAt: 23,
                endAt: 37,
                required: true,
                default: 0,
            },
            {
                fieldId: 1104,
                description: 'קבוע מערכת',
                type: 'string',
                length: 8,
                startAt: 38,
                endAt: 45,
                required: true,
                default: 0,
            },
            {
                fieldId: 1105,
                description: 'שטח לנתונים עתידיים',
                type: 'string',
                length: 50,
                startAt: 46,
                endAt: 95,
                required: true,
                default: '',
            },
        ],
    },
    footer: {
        cells: [
            {
                fieldId: 1150,
                description: 'קוד רשומה',
                type: 'string',
                length: 4,
                startAt: 1,
                endAt: 4,
                required: true,
                default: 'Z900',
            },
            {
                fieldId: 1151,
                description: 'מס רשומה בקובץ',
                type: 'number',
                length: 9,
                startAt: 5,
                endAt: 13,
                required: true,
                default: 0,
            },
            {
                fieldId: 1152,
                description: 'מספר עוסק מורשה',
                type: 'number',
                length: 9,
                startAt: 14,
                endAt: 22,
                required: true,
                default: 0,
            },
            {
                fieldId: 1153,
                name: 'uuid',
                description: 'מזהה ראשי',
                type: 'number',
                length: 15,
                startAt: 23,
                endAt: 37,
                required: true,
                default: 0,
            },
            {
                fieldId: 1154,
                description: 'קבוע מערכת',
                type: 'string',
                length: 8,
                startAt: 38,
                endAt: 45,
                required: true,
                default: 0,
            },
            {
                fieldId: 1155,
                description: 'סך רשומות כולל בקובץ',
                type: 'number',
                length: 15,
                startAt: 46,
                endAt: 60,
                required: true,
                default: 0,
            },
            {
                fieldId: 1155,
                description: 'שטח לנתונים עתידיים',
                type: 'string',
                length: 50,
                startAt: 61,
                endAt: 110,
                required: true,
                default: '',
            },
        ],
    },
    c100Row: {
        cells: [
            {
                fieldId: 1200,
                description: 'קוד רשומה',
                type: 'string',
                length: 4,
                startAt: 1,
                endAt: 4,
                required: true,
                default: 'C100',
            },
            {
                fieldId: 1201,
                description: 'מס רשומה בקובץ',
                type: 'number',
                length: 9,
                startAt: 5,
                endAt: 13,
                required: true,
                default: 0,
            },
            {
                fieldId: 1202,
                description: 'מספר עוסק מורשה',
                type: 'number',
                length: 9,
                startAt: 14,
                endAt: 22,
                required: true,
                default: 0,
            }, {
                fieldId: 1203,
                description: 'סוג מסמך',
                type: 'string',
                length: 3,
                startAt: 23,
                endAt: 25,
                required: true,
                default: 0,
            },
            {
                fieldId: 1204,
                description: 'מספר מסמך',
                type: 'string',
                length: 20,
                startAt: 26,
                endAt: 45,
                required: true,
                default: 0,
            },
            {
                fieldId: 1205,
                description: 'תאריך הפקת מסמך',
                type: 'number',
                length: 8,
                startAt: 46,
                endAt: 53,
                required: true,
                default: 0,
            },
            {
                fieldId: 1206,
                description: 'שעת הפקת מסמך',
                type: 'number',
                length: 4,
                startAt: 54,
                endAt: 57,
                required: true,
                default: 0,
            }, {

                fieldId: 1207,
                description: 'שם לקוח/ספק',
                type: 'string',
                length: 50,
                startAt: 58,
                endAt: 107,
                required: true,
                default: '',
            },
            {
                fieldId: 1208,
                description: 'מען הלקוח/ספק - רחוב',
                type: 'string',
                length: 50,
                startAt: 108,
                endAt: 157,
                required: false,
                default: '',
            }, {
                fieldId: 1209,
                description: 'מען הלקוח/ספק - מס בית',
                type: 'string',
                length: 10,
                startAt: 158,
                endAt: 167,
                required: false,
                default: '',
            }, {
                fieldId: 1210,
                description: 'מען הלקוח/ספק - עיר',
                type: 'string',
                length: 30,
                startAt: 168,
                endAt: 197,
                required: false,
                default: '',
            }, {
                fieldId: 1211,
                description: 'מען הלקוח/ספק - מיקוד',
                type: 'string',
                length: 8,
                startAt: 198,
                endAt: 205,
                required: false,
                default: '',
            }, {
                fieldId: 1212,
                description: 'מען הלקוח/ספק - מדינה',
                type: 'string',
                length: 30,
                startAt: 206,
                endAt: 235,
                required: false,
                default: '',

            }, {
                fieldId: 1213,
                description: 'מען הלקוח/ספק - קוד מדינה',
                type: 'string',
                length: 2,
                startAt: 236,
                endAt: 237,
                required: false,
                default: '',
            }, {
                fieldId: 1214,
                description: 'טלפון לקוח/ספק',
                type: 'string',
                length: 15,
                startAt: 238,
                endAt: 252,
                required: false,
                default: '',
            }, {
                fieldId: 1215,
                description: 'מס עוסק מורשה לקוח/ספק',
                type: 'string',
                length: 9,
                startAt: 253,
                endAt: 261,
                required: false,
                default: '',
            },
            {
                fieldId: 1216,
                description: 'תאריך ערך',
                type: 'number',
                length: 8,
                startAt: 262,
                endAt: 269,
                required: true,
                default: 0,
            }, {
                fieldId: 1217,
                description: 'סכום סופי של המסמך במט"ח',
                type: 'string',
                length: 15,
                startAt: 270,
                endAt: 284,
                required: true,
                default: 0,
            }, {
                fieldId: 1218,
                description: 'קוד מט"ח',
                type: 'string',
                length: 3,
                startAt: 285,
                endAt: 287,
                required: true,
                default: 0,
            },
            {
                fieldId: 1219,
                description: 'סכום המסמך לפני הנחת מסמך',
                type: 'string',
                length: 15,
                startAt: 288,
                endAt: 302,
                required: true,
                default: 0,
            }, {
                fieldId: 1220,
                description: 'הנחת מסמך',
                type: 'string',
                length: 15,
                startAt: 303,
                endAt: 317,
                required: true,
                default: 0,
            },
            {
                fieldId: 1221,
                description: 'סכום המסמך לאחר הנחות ללא מע"מ',
                type: 'string',
                length: 15,
                startAt: 318,
                endAt: 332,
                required: true,
                default: 0,
            }, {
                fieldId: 1222,
                description: 'סכום המע"מ',
                type: 'string',
                length: 15,
                startAt: 333,
                endAt: 347,
                required: true,
                default: 0,
            }, {
                fieldId: 1223,
                description: 'סכום המסמך כולל מע"מ',
                type: 'string',
                length: 15,
                startAt: 348,
                endAt: 362,
                required: true,
                default: 0,
            }, {
                fieldId: 1224,
                description: 'סכום הניכוי במקור',
                type: 'string',
                length: 12,
                startAt: 363,
                endAt: 374,
                required: true,
                default: 0,
            }, {
                fieldId: 1225,
                description: 'מפתח הלקוח אצל המוכר או מפתח הספק אצל הקונה',
                type: 'string',
                length: 15,
                startAt: 375,
                endAt: 389,
                required: false,
                default: '',
            }, {
                fieldId: 1226,
                description: 'שדה התאמה',
                type: 'string',
                length: 10,
                startAt: 390,
                endAt: 399,
                required: false,
                default: '',
            },
            {
                fieldId: 1228,
                description: 'מסמך מבוטל',
                type: 'string', // 1
                length: 1,
                startAt: 400,
                endAt: 400,
                required: false,
                default: '',
            },
            {
                fieldId: 1230,
                description: 'תאריך המסמך',
                type: 'number',
                length: 8,
                startAt: 401,
                endAt: 408,
                required: true,
                default: 0,
            },
            {
                fieldId: 1231,
                description: 'מזהה סניף/ענף',
                type: 'string',
                length: 7,
                startAt: 409,
                endAt: 415,
                required: false,
                default: '',
            },
            {
                fieldId: 1233,
                description: 'מבצע הפעולה',
                type: 'string',
                length: 9,
                startAt: 416,
                endAt: 424,
                required: false,
                default: '',
            },
            {
                fieldId: 1234,
                description: 'שדה מקשר לשורה',
                type: 'number',
                length: 7,
                startAt: 425,
                endAt: 431,
                required: false,
                default: '',
            }, {
                fieldId: 1235,
                description: 'שטח לנתונים עתידיים',
                type: 'string',
                length: 13,
                startAt: 432,
                endAt: 444,
                required: false,
                default: '',
            },
        ],
    },
    D110Row: {
        cells: [
            {
                "default": "D110",
                "required": true,
                "length": 4,
                "startAt": 1,
                "endAt": 4,
                "type": "string",
                "description": "קוד רשומה",
                "fieldId": 1250
            },
            {
                "default": "מס רץ של הרשומה בקובץ BKMVDATA",
                "required": true,
                "length": 9,
                "startAt": 5,
                "endAt": 13,
                "type": "number",
                "description": "מס רשומה בקובץ",
                "fieldId": 1251
            },
            {
                "default": "מספר עוסק מורשה של בית העסק",
                "required": true,
                "length": 9,
                "startAt": 14,
                "endAt": 22,
                "type": "number",
                "description": "מס עוסק מורשה",
                "fieldId": 1252
            },
            {
                "default": "בהתאם לרשימת מסמכים בטבלה בנספח\nמספר 1",
                "required": true,
                "length": 3,
                "startAt": 23,
                "endAt": 25,
                "type": "number",
                "description": "סוג המסמך",
                "fieldId": 1253
            },
            {
                "default": "",
                "required": true,
                "length": 20,
                "startAt": 26,
                "endAt": 45,
                "type": "string",
                "description": "מספר המסמך",
                "fieldId": 1254
            },
            {
                "default": "",
                "required": true,
                "length": 4,
                "startAt": 46,
                "endAt": 49,
                "type": "number",
                "description": "מספר שורה במסמך",
                "fieldId": 1255
            },
            {
                "default": "בהתאם לרשימת מסמכים בנספח ;1 חובה כאשר המסמך מבוסס על מסמך אחר, ראה הבהרה 6 בנספח הבהרות",
                "required": true,
                "length": 3,
                "startAt": 50,
                "endAt": 52,
                "type": "number",
                "description": "סוג מסמך בסיס",
                "fieldId": 1256
            },
            {
                "default": "בהתאם לרשימת מסמכים בנספח ;1 חובה כאשר המסמך מבוסס על מסמך אחר, ראה הבהרה 6 בנספח הבהרות",
                "required": true,
                "length": 20,
                "startAt": 53,
                "endAt": 72,
                "type": "string",
                "description": "מספר מסמך בסיס",
                "fieldId": 1257
            },
            {
                "default": "1 - שירות; 2 - מכר; 3 - שירות ומכר",
                "required": true,
                "length": 1,
                "startAt": 73,
                "endAt": 73,
                "type": "number",
                "description": "סוג עסקה",
                "fieldId": 1258
            },
            {
                "default": "",
                "required": true,
                "length": 20,
                "startAt": 74,
                "endAt": 93,
                "type": "string",
                "description": "מק\"ט פנימי",
                "fieldId": 1259
            },
            {
                "default": "",
                "required": true,
                "length": 30,
                "startAt": 94,
                "endAt": 123,
                "type": "string",
                "description": "תיאור הטובין שנמכר או\nהשירות שניתן",
                "fieldId": 1260
            },
            {
                "default": "לגבי טובין המפורטים בנספח ג' בהוראה\n36 להוראות ניהול פנקסים",
                "required": true,
                "length": 50,
                "startAt": 124,
                "endAt": 173,
                "type": "string",
                "description": "שם היצרן",
                "fieldId": 1261
            },
            {
                "default": "לגבי טובין המפורטים בנספח ג' בהוראה\n36 להוראות ניהול פנקסים",
                "required": true,
                "length": 30,
                "startAt": 174,
                "endAt": 203,
                "type": "string",
                "description": "מספר סידורי של המוצר המוטבע על המוצר על ידי\nהיצרן",
                "fieldId": 1262
            },
            {
                "default": "כשמדובר ביחידה עם משמעות )לדוגמא ליטר, גרם, שעת עבודה( ירשם תיאור היחידה, אחרת\nתרשם המילה \"יחידה",
                "required": true,
                "length": 20,
                "startAt": 204,
                "endAt": 223,
                "type": "string",
                "description": "תיאור יחידת המידה",
                "fieldId": 1263
            },
            {
                "default": "",
                "required": true,
                "length": 17,
                "startAt": 224,
                "endAt": 240,
                "type": "string",
                "description": "הכמות",
                "fieldId": 1264
            },
            {
                "default": "סכום בש \"ח",
                "required": true,
                "length": 15,
                "startAt": 241,
                "endAt": 255,
                "type": "string",
                "description": "מחיר ליחידה ללא מע\"מ",
                "fieldId": 1265
            },
            {
                "default": "סכום בש\"ח. ראה הבהרה 5 בנספח\nהבהרות",
                "required": true,
                "length": 15,
                "startAt": 256,
                "endAt": 270,
                "type": "string",
                "description": "הנחת שורה",
                "fieldId": 1266
            },
            {
                "default": "הכמות בשורה * מחיר ליח' ללא מע\"מ\nבניכוי הנחת השורה",
                "required": true,
                "length": 15,
                "startAt": 271,
                "endAt": 285,
                "type": "string",
                "description": "סך סכום לשורה",
                "fieldId": 1267
            },
            {
                "default": "מספר המייצג אחוז ) 1550 (",
                "required": true,
                "length": 4,
                "startAt": 286,
                "endAt": 289,
                "type": "number",
                "description": "שיעור המע\"מ בשורה",
                "fieldId": 1268
            },
            {
                "default": "מספר הסניף/ענף כפי שמופיע ברישומי בית העסק; חובה כאשר ערך שדה 1=1034 , ראה\nהבהרה 3 בנספח הבהרות.",
                "required": true,
                "length": 7,
                "startAt": 290,
                "endAt": 296,
                "type": "string",
                "description": "מזהה סניף/ענף",
                "fieldId": 1270
            },
            {
                "default": "בפורמט .YYYYMMDD ראה הבהרה 12\nבנספח הבהרות.",
                "required": true,
                "length": 8,
                "startAt": 297,
                "endAt": 304,
                "type": "number",
                "description": "תאריך המסמך",
                "fieldId": 1272
            },
            {
                "default": "המספר הפנימי שמפיקה התוכנה לצורך קישור בין שורות המסמך לכותרת המסמך.ראה\nהבהרה 11 בנספח הבהרות.",
                "required": true,
                "length": 7,
                "startAt": 305,
                "endAt": 311,
                "type": "number",
                "description": "שדה מקשר לכותרת",
                "fieldId": 1273
            },
            {
                "default": "מספר הסניף/ענף של מ. בסיס כפי שמופיע ברישומי בית העסק; חובה כאשר ערך שדה\n1=1034 , ראה הבהרות 3 ו 6 בנספח הבהרות.",
                "required": true,
                "length": 7,
                "startAt": 312,
                "endAt": 318,
                "type": "string",
                "description": "מזהה סניף/ענף למסמך\nבסיס",
                "fieldId": 1274
            },
            {
                "default": "",
                "required": true,
                "length": 21,
                "startAt": 319,
                "endAt": 339,
                "type": "string",
                "description": "שטח לנתונים עתידיים",
                "fieldId": 1275
            }
        ],
    },
    D120Row: {
        cells: [
            {
                "default": "D120",
                "required": true,
                "length": 4,
                "startAt": 1,
                "endAt": 4,
                "type": "string",
                "description": "קוד רשומה",
                "fieldId": 1300
            },
            {
                "default": "מס רץ של הרשומה בקובץ BKMVDATA",
                "required": true,
                "length": 9,
                "startAt": 5,
                "endAt": 13,
                "type": "number",
                "description": "מס רשומה בקובץ",
                "fieldId": 1301
            },
            {
                "default": "מספר עוסק מורשה של בית העסק",
                "required": true,
                "length": 9,
                "startAt": 14,
                "endAt": 22,
                "type": "number",
                "description": "מס עוסק מורשה",
                "fieldId": 1302
            },
            {
                "default": "בהתאם לרשימת מסמכים בטבלה בנספח מספר 1 ,ראה הבהרה 1 בנספח הבהרות",
                "required": true,
                "length": 3,
                "startAt": 23,
                "endAt": 25,
                "type": "number",
                "description": "סוג מסמך",
                "fieldId": 1303
            },
            {
                "default": "",
                "required": true,
                "length": 20,
                "startAt": 26,
                "endAt": 45,
                "type": "string",
                "description": "מספר מסמך",
                "fieldId": 1304
            },
            {
                "default": "",
                "required": true,
                "length": 4,
                "startAt": 46,
                "endAt": 49,
                "type": "number",
                "description": "מספר שורה במסמך",
                "fieldId": 1305
            },
            {
                "default": "-1 מזומן; 2 - המחאה; 3 - כ. אשראי; 4 - העב.\nבנקאית; 5 - תווי קניה; 6 -תלוש החלפה; 7 -\nשטר; -8ה.קבע9; -אחר",
                "required": true,
                "length": 1,
                "startAt": 50,
                "endAt": 50,
                "type": "number",
                "description": "סוג אמצעי התשלום",
                "fieldId": 1306
            },
            {
                "default": "בהמחאה בלבד",
                "required": false,
                "length": 10,
                "startAt": 51,
                "endAt": 60,
                "type": "number",
                "description": "מספר הבנק",
                "fieldId": 1307
            },
            {
                "default": "בהמחאה בלבד",
                "required": false,
                "length": 10,
                "startAt": 61,
                "endAt": 70,
                "type": "number",
                "description": "מספר הסניף",
                "fieldId": 1308
            },
            {
                "default": "בהמחאה בלבד",
                "required": false,
                "length": 15,
                "startAt": 71,
                "endAt": 85,
                "type": "number",
                "description": "מספר חשבון",
                "fieldId": 1309
            },
            {
                "default": "בהמחאה בלבד",
                "required": false,
                "length": 10,
                "startAt": 86,
                "endAt": 95,
                "type": "number",
                "description": "מספר המחאה",
                "fieldId": 1310
            },
            {
                "default": "בפורמט ,YYYYMMDD בהמחאה או\nבכרטיס אשראי בלבד",
                "required": true,
                "length": 8,
                "startAt": 96,
                "endAt": 103,
                "type": "number",
                "description": "תאריך הפירעון של ההמחאה /\nהתשלום",
                "fieldId": 1311
            },
            {
                "default": "",
                "required": true,
                "length": 15,
                "startAt": 104,
                "endAt": 118,
                "type": "string",
                "description": "סכום השורה",
                "fieldId": 1312
            },
            {
                "default": "-1ישראכרט, -2כאל, -3דיינרס, -4 אמריקן\nאקספרס, -6לאומי כארד",
                "required": true,
                "length": 1,
                "startAt": 119,
                "endAt": 119,
                "type": "number",
                "description": "קוד החברה הסולקת",
                "fieldId": 1313
            },
            {
                "default": "",
                "required": true,
                "length": 20,
                "startAt": 120,
                "endAt": 139,
                "type": "string",
                "description": "שם הכרטיס הנסלק",
                "fieldId": 1314
            },
            {
                "default": "1 - רגיל; 2 - תשלומים; 3 - קרדיט-4;חיוב נדחה;\n-5אחר",
                "required": true,
                "length": 1,
                "startAt": 140,
                "endAt": 140,
                "type": "number",
                "description": "סוג עסקת האשראי",
                "fieldId": 1315
            },
            {
                "default": "מספר הסניף/ענף כפי שמופיע ברישומי בית\nהעסק; חובה כאשר ערכו של שדה 1034 הוא ,1\nראה הבהרה 3 בנספח הבהרות",
                "required": true,
                "length": 7,
                "startAt": 141,
                "endAt": 147,
                "type": "string",
                "description": "מזהה סניף/ענף",
                "fieldId": 1320
            },
            {
                "default": "בפורמט .YYYYMMDD ראה הבהרה 12\nבנספח הבהרות.",
                "required": true,
                "length": 8,
                "startAt": 148,
                "endAt": 155,
                "type": "number",
                "description": "תאריך המסמך",
                "fieldId": 1322
            },
            {
                "default": "המספר הפנימי שמפיקה התוכנה לצורך קישור בין שורות המסמך לכותרת המסמך.ראה הבהרה\n11 בנספח הבהרות.",
                "required": true,
                "length": 7,
                "startAt": 156,
                "endAt": 162,
                "type": "number",
                "description": "שדה מקשר לכותרת",
                "fieldId": 1323
            },
            {
                "default": "",
                "required": true,
                "length": 60,
                "startAt": 163,
                "endAt": 222,
                "type": "string",
                "description": "שטח לנתונים עתידיים",
                "fieldId": 1324
            }
        ],
    },
    B100Row: {
        cells: [
            {
                "default": "B100",
                "required": true,
                "length": 4,
                "startAt": 1,
                "endAt": 4,
                "type": "string",
                "description": "קוד רשומה",
                "fieldId": 1350
            },
            {
                "default": "מס רץ של הרשומה בקובץ BKMVDATA",
                "required": true,
                "length": 9,
                "startAt": 5,
                "endAt": 13,
                "type": "number",
                "description": "מס רשומה בקובץ",
                "fieldId": 1351
            },
            {
                "default": "מספר עוסק מורשה של בית העסק",
                "required": true,
                "length": 9,
                "startAt": 14,
                "endAt": 22,
                "type": "number",
                "description": "מס עוסק מורשה",
                "fieldId": 1352
            },
            {
                "default": "ראה הבהרה 7 בנספח הבהרות.",
                "required": true,
                "length": 10,
                "startAt": 23,
                "endAt": 32,
                "type": "number",
                "description": "מספר תנועה",
                "fieldId": 1353
            },
            {
                "default": "",
                "required": true,
                "length": 5,
                "startAt": 33,
                "endAt": 37,
                "type": "number",
                "description": "מספר שורה בתנועה",
                "fieldId": 1354
            },
            {
                "default": "",
                "required": true,
                "length": 8,
                "startAt": 38,
                "endAt": 45,
                "type": "number",
                "description": "מנה",
                "fieldId": 1355
            },
            {
                "default": "",
                "required": true,
                "length": 15,
                "startAt": 46,
                "endAt": 60,
                "type": "string",
                "description": "סוג תנועה",
                "fieldId": 1356
            },
            {
                "default": "בהתאם לטבלת עזר המפורטת בנספח מספר .1 אם רישום האסמכתא הוא תוצר של תהליך\nמובנה בתוכנה ולכן סוג המסמך ידוע.",
                "required": true,
                "length": 20,
                "startAt": 61,
                "endAt": 80,
                "type": "string",
                "description": "אסמכתא",
                "fieldId": 1357
            },
            {
                "default": "",
                "required": true,
                "length": 3,
                "startAt": 81,
                "endAt": 83,
                "type": "number",
                "description": "סוג מסמך האסמכתא",
                "fieldId": 1358
            },
            {
                "default": "בהתאם לטבלת עזר המפורטת בנספח מספר .1 אם רישום האסמכתא הוא תוצר של תהליך\nמובנה בתוכנה ולכן סוג המסמך ידוע.",
                "required": true,
                "length": 20,
                "startAt": 84,
                "endAt": 103,
                "type": "string",
                "description": "אסמכתא 2",
                "fieldId": 1359
            },
            {
                "default": "",
                "required": true,
                "length": 3,
                "startAt": 104,
                "endAt": 106,
                "type": "number",
                "description": "סוג מסמך האסמכתא\n2",
                "fieldId": 1360
            },
            {
                "default": "",
                "required": true,
                "length": 50,
                "startAt": 107,
                "endAt": 156,
                "type": "string",
                "description": "פרטים",
                "fieldId": 1361
            },
            {
                "default": "בפורמט ,YYYYMMDD ראה הבהרה 12\nבנספח הבהרות",
                "required": true,
                "length": 8,
                "startAt": 157,
                "endAt": 164,
                "type": "number",
                "description": "תאריך",
                "fieldId": 1362
            },
            {
                "default": "בפורמט ,YYYYMMDD ראה הבהרה 12\nבנספח הבהרות",
                "required": true,
                "length": 8,
                "startAt": 165,
                "endAt": 172,
                "type": "number",
                "description": "תאריך ערך",
                "fieldId": 1363
            },
            {
                "default": "מפתח החשבון; לערך שדה זה חייבת להיות\nרשומה מסוג B110",
                "required": true,
                "length": 15,
                "startAt": 173,
                "endAt": 187,
                "type": "string",
                "description": "חשבון בתנועה",
                "fieldId": 1364
            },
            {
                "default": "מפתח החשבון . בהנהלת חשבונות חד צידית בלבד, אם קיים. לערך שדה זה חייבת להיות\nרשומה מסוג B110",
                "required": true,
                "length": 15,
                "startAt": 188,
                "endAt": 202,
                "type": "string",
                "description": "חשבון נגדי",
                "fieldId": 1365
            },
            {
                "default": "1 - חובה, הוצאה; 2 - זכות, הכנסה",
                "required": true,
                "length": 1,
                "startAt": 203,
                "endAt": 203,
                "type": "number",
                "description": "סימן הפעולה",
                "fieldId": 1366
            },
            {
                "default": "בהתאם לטבלת קוד מטבע בנספח מספר .2 מתייחס לסכום המופיע בשדה 1369",
                "required": true,
                "length": 3,
                "startAt": 204,
                "endAt": 206,
                "type": "string",
                "description": "קוד מטבע מטח",
                "fieldId": 1367
            },
            {
                "default": "במטבע מוביל",
                "required": true,
                "length": 15,
                "startAt": 207,
                "endAt": 221,
                "type": "string",
                "description": "סכום הפעולה",
                "fieldId": 1368
            },
            {
                "default": "",
                "required": true,
                "length": 15,
                "startAt": 222,
                "endAt": 236,
                "type": "string",
                "description": "סכום מטח",
                "fieldId": 1369
            },
            {
                "default": "עשוי לשמש לדוגמא לציון כמות ע\"נ או קוד\nתמחיר",
                "required": true,
                "length": 12,
                "startAt": 237,
                "endAt": 248,
                "type": "string",
                "description": "שדה כמות",
                "fieldId": 1370
            },
            {
                "default": "מספר זיהוי להתאמת שורות בתוך כרטיס,\nלמשל התאמת עסקת חו\"ז.",
                "required": true,
                "length": 10,
                "startAt": 249,
                "endAt": 258,
                "type": "string",
                "description": "שדה התאמה 1",
                "fieldId": 1371
            },
            {
                "default": "מספר זיהוי להתאמת שורות בכרטיס לשורות בכרטיס אחר או כרטיס חיצוני, למשל התאמת\nבנק.",
                "required": true,
                "length": 10,
                "startAt": 259,
                "endAt": 268,
                "type": "string",
                "description": "שדה התאמה 2",
                "fieldId": 1372
            },
            {
                "default": "שדה מבוטל!",
                "required": true,
                "length": 0,
                "startAt": 269,
                "endAt": 269,
                "type": "string",
                "description": "שטח לנתונים \nעתידיים",
                "fieldId": 1373
            },
            {
                "default": "מספר הסניף/הענף כפי שמופיע ברישומי בית\nהעסק; חובה כאשר ערכו של שדה 1034 הוא ,1\nראה הבהרה 3 בנספח הבהרות",
                "required": true,
                "length": 7,
                "startAt": 269,
                "endAt": 275,
                "type": "string",
                "description": "מזהה סניף/ענף",
                "fieldId": 1374
            },
            {
                "default": "ראה הבהרה מספר 12 בנספח ההבהרות",
                "required": true,
                "length": 8,
                "startAt": 276,
                "endAt": 283,
                "type": "number",
                "description": "תאריך הזנה",
                "fieldId": 1375
            },
            {
                "default": "שם המשתמש של מבצע הפעולה",
                "required": true,
                "length": 9,
                "startAt": 284,
                "endAt": 292,
                "type": "string",
                "description": "מבצע פעולה",
                "fieldId": 1376
            },
            {
                "default": "",
                "required": true,
                "length": 25,
                "startAt": 293,
                "endAt": 317,
                "type": "string",
                "description": "שטח לנתונים עתידיים",
                "fieldId": 1377
            }
        ],
    },
    B110Row: {
        cells: [
            {
                "default": "B110",
                "required": true,
                "length": 4,
                "startAt": 1,
                "endAt": 4,
                "type": "string",
                "description": "קוד רשומה",
                "fieldId": 1400
            },
            {
                "default": "מס רץ של הרשומה בקובץ\nBKMVDATA",
                "required": true,
                "length": 9,
                "startAt": 5,
                "endAt": 13,
                "type": "number",
                "description": "מס רשומה בקובץ",
                "fieldId": 1401
            },
            {
                "default": "מספר עוסק מורשה של בית העסק",
                "required": true,
                "length": 9,
                "startAt": 14,
                "endAt": 22,
                "type": "number",
                "description": "מס עוסק מורשה",
                "fieldId": 1402
            },
            {
                "default": "ערך השדה חד חד ערכי",
                "required": true,
                "length": 15,
                "startAt": 23,
                "endAt": 37,
                "type": "string",
                "description": "מפתח החשבון",
                "fieldId": 1403
            },
            {
                "default": "",
                "required": true,
                "length": 50,
                "startAt": 38,
                "endAt": 87,
                "type": "string",
                "description": "שם החשבון",
                "fieldId": 1404
            },
            {
                "default": "",
                "required": true,
                "length": 15,
                "startAt": 88,
                "endAt": 102,
                "type": "string",
                "description": "קוד מאזן בוחן",
                "fieldId": 1405
            },
            {
                "default": "",
                "required": true,
                "length": 30,
                "startAt": 103,
                "endAt": 132,
                "type": "string",
                "description": "תיאור קוד מאזן בוחן",
                "fieldId": 1406
            },
            {
                "default": "ברשומת חשבון של לקוח או ספק",
                "required": true,
                "length": 50,
                "startAt": 133,
                "endAt": 182,
                "type": "string",
                "description": "מען הלקוח/ספק - רחוב",
                "fieldId": 1407
            },
            {
                "default": "ברשומת חשבון של לקוח או ספק",
                "required": true,
                "length": 10,
                "startAt": 183,
                "endAt": 192,
                "type": "string",
                "description": "מען הלקוח/ספק - מספר בית",
                "fieldId": 1408
            },
            {
                "default": "ברשומת חשבון של לקוח או ספק",
                "required": true,
                "length": 30,
                "startAt": 193,
                "endAt": 222,
                "type": "string",
                "description": "מען הלקוח/ספק - עיר",
                "fieldId": 1409
            },
            {
                "default": "ברשומת חשבון של לקוח או ספק",
                "required": true,
                "length": 8,
                "startAt": 223,
                "endAt": 230,
                "type": "string",
                "description": "מען הלקוח/ספק - מיקוד",
                "fieldId": 1410
            },
            {
                "default": "ברשומת חשבון של לקוח או ספק",
                "required": true,
                "length": 30,
                "startAt": 231,
                "endAt": 260,
                "type": "string",
                "description": "מען הלקוח/ספק - מדינה",
                "fieldId": 1411
            },
            {
                "default": "ברשומת חשבון של לקוח או ספק",
                "required": true,
                "length": 2,
                "startAt": 261,
                "endAt": 262,
                "type": "string",
                "description": "קוד מדינה",
                "fieldId": 1412
            },
            {
                "default": "",
                "required": true,
                "length": 15,
                "startAt": 263,
                "endAt": 277,
                "type": "string",
                "description": "חשבון מרכז",
                "fieldId": 1413
            },
            {
                "default": "שדה מחושב לפי תאריך החיתוך של\nהנתונים ) \"+\" - יתרת חובה; \"-\" -\nיתרת זכות (",
                "required": true,
                "length": 15,
                "startAt": 278,
                "endAt": 292,
                "type": "string",
                "description": "יתרת החשבון בתחילת החתך",
                "fieldId": 1414
            },
            {
                "default": "סך כספי של תנועות החובה ללא\nיתרת פתיחה",
                "required": true,
                "length": 15,
                "startAt": 293,
                "endAt": 307,
                "type": "string",
                "description": "סה\"כ חובה",
                "fieldId": 1415
            },
            {
                "default": "סך כספי של תנועות הזכות ללא\nיתרת פתיחה",
                "required": true,
                "length": 15,
                "startAt": 308,
                "endAt": 322,
                "type": "string",
                "description": "סה\"כ זכות",
                "fieldId": 1416
            },
            {
                "default": "בהתאם לטופס ;6111 חובה כאשר הנישום חייב בדיווח כזה",
                "required": true,
                "length": 4,
                "startAt": 323,
                "endAt": 326,
                "type": "number",
                "description": "קוד בסיווג החשבונאי",
                "fieldId": 1417
            },
            {
                "default": "ציון מספר עוסק מורשה של הספק\nחובה אם הנישום מנהל הנהלת חשבונות כפולה )קוד 2 בשדה 1013\n.(",
                "required": true,
                "length": 9,
                "startAt": 327,
                "endAt": 335,
                "type": "number",
                "description": "מספר עוסק של ספק/לקוח",
                "fieldId": 1419
            },
            {
                "default": "מספר הסניף/ענף כפי שמופיע ברישומי בית העסק; חובה כאשר ערכו של שדה 1034 הוא 1 , ראה הבהרה 3 בנספח\nהבהרות",
                "required": true,
                "length": 7,
                "startAt": 336,
                "endAt": 342,
                "type": "string",
                "description": "מזהה סניף/ענף",
                "fieldId": 1421
            },
            {
                "default": "",
                "required": true,
                "length": 15,
                "startAt": 343,
                "endAt": 357,
                "type": "string",
                "description": "יתרת חשבון בתחילת חתך\nבמט\"ח",
                "fieldId": 1422
            },
            {
                "default": "בהתאם לטבלת קוד מטבע בנספח מספר .2 מתייחס לסכום המופיע\nבשדה 1422",
                "required": true,
                "length": 3,
                "startAt": 358,
                "endAt": 360,
                "type": "string",
                "description": "קוד מטבע יתרת החשבון בתחילת חתך במט\"ח",
                "fieldId": 1423
            },
            {
                "default": "",
                "required": true,
                "length": 16,
                "startAt": 361,
                "endAt": 376,
                "type": "string",
                "description": "שטח לנתונים עתידיים",
                "fieldId": 1424
            }
        ],
    },
    M100Row: {
        cells: [
            {
                "default": "M100",
                "required": true,
                "length": 4,
                "startAt": 1,
                "endAt": 4,
                "type": "string",
                "description": "קוד רשומה",
                "fieldId": 1450
            },
            {
                "default": "מס רץ של הרשומה בקובץ\nBKMVDATA",
                "required": true,
                "length": 9,
                "startAt": 5,
                "endAt": 13,
                "type": "number",
                "description": "מס רשומה בקובץ",
                "fieldId": 1451
            },
            {
                "default": "מספר עוסק מורשה של בית העסק",
                "required": true,
                "length": 9,
                "startAt": 14,
                "endAt": 22,
                "type": "number",
                "description": "מס עוסק מורשה",
                "fieldId": 1452
            },
            {
                "default": "",
                "required": true,
                "length": 20,
                "startAt": 23,
                "endAt": 42,
                "type": "string",
                "description": "מק\"ט פריט אוניברסלי",
                "fieldId": 1453
            },
            {
                "default": "",
                "required": true,
                "length": 20,
                "startAt": 43,
                "endAt": 62,
                "type": "string",
                "description": "מק\"ט הספק/יצרן ) במסמכי רכש (",
                "fieldId": 1454
            },
            {
                "default": "ערך השדה חד חד ערכי",
                "required": true,
                "length": 20,
                "startAt": 63,
                "endAt": 82,
                "type": "string",
                "description": "מק\"ט פנימי",
                "fieldId": 1455
            },
            {
                "default": "",
                "required": true,
                "length": 50,
                "startAt": 83,
                "endAt": 132,
                "type": "string",
                "description": "שם פריט",
                "fieldId": 1456
            },
            {
                "default": "",
                "required": true,
                "length": 10,
                "startAt": 133,
                "endAt": 142,
                "type": "string",
                "description": "קוד מיון",
                "fieldId": 1457
            },
            {
                "default": "",
                "required": true,
                "length": 30,
                "startAt": 143,
                "endAt": 172,
                "type": "string",
                "description": "תיאור קוד מיון",
                "fieldId": 1458
            },
            {
                "default": "כשמדובר ביחידה עם משמעות )לדוגמא : ליטר, גרם, שעת עבודה( ירשם תיאור היחידה, אחרת תרשם\nהמילה \"יחידה",
                "required": true,
                "length": 20,
                "startAt": 173,
                "endAt": 192,
                "type": "string",
                "description": "תיאור יחידת מידה",
                "fieldId": 1459
            },
            {
                "default": "בכל המחסנים",
                "required": true,
                "length": 12,
                "startAt": 193,
                "endAt": 204,
                "type": "string",
                "description": "יתרת הפריט לתחילת\nהחתך",
                "fieldId": 1460
            },
            {
                "default": "סך הכניסות בטווח , ללא יתרת פתיחה",
                "required": true,
                "length": 12,
                "startAt": 205,
                "endAt": 216,
                "type": "string",
                "description": "סך הכל כניסות",
                "fieldId": 1461
            },
            {
                "default": "סך היציאות בטווח , ללא יתרת פתיחה",
                "required": true,
                "length": 12,
                "startAt": 217,
                "endAt": 228,
                "type": "string",
                "description": "סך הכל יציאות",
                "fieldId": 1462
            },
            {
                "default": "סכום בש\"ח, ראה הבהרה 9 בנספח\nהבהרות",
                "required": true,
                "length": 10,
                "startAt": 229,
                "endAt": 238,
                "type": "number",
                "description": "מחיר עלות במלאי לסוף תקופת החתך מחוץ למחסני ערובה",
                "fieldId": 1463
            },
            {
                "default": "סכום בש\"ח, ראה הבהרה 10 בנספח\nהבהרות",
                "required": true,
                "length": 10,
                "startAt": 239,
                "endAt": 248,
                "type": "number",
                "description": "מחיר עלות במלאי לסוף תקופת החתך במחסני\nערובה",
                "fieldId": 1464
            },
            {
                "default": "",
                "required": true,
                "length": 50,
                "startAt": 249,
                "endAt": 298,
                "type": "string",
                "description": "שטח לנתונים עתידיים",
                "fieldId": 1465
            }
        ],
    },
}
